<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WallpaperCardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('truncate table wallpaper_cards');
        DB::table('wallpaper_cards')->insert([
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/wallpaper.jpg', 'name' => 'sky tree', 'free_price' => 'free',  'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/cyberpunk1.jpg', 'name' => 'Cyber punk women', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/windows_11.jpg', 'name' => 'windows 11', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sofa.png', 'name' => 'home sofa', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sky.jpg', 'name' => 'night sky', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/NIGA.jpg', 'name' => 'black man', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/winter_tree.jpg', 'name' => 'winter tree', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sea.jpg', 'name' => 'blue sea', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rols.jpg', 'name' => 'drift rols', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/anime.jpg', 'name' => 'anime gearls', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/big_smoke.jpg', 'name' => 'big smoke', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/game_pad.jpg', 'name' => 'game pad sony', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/trees.jpeg', 'name' => 'trees view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view.jpg', 'name' => 'purple view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/purple_tree.jpg', 'name' => 'moon tree', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gta_band.jpg', 'name' => 'gta band', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/silvia.jpg', 'name' => 'silvia s15', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/anime2.jpg', 'name' => 'anime man', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/cyberpunk2.jpg', 'name' => 'cyberpunk women', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/silvia2.jpg', 'name' => 'silvia s15', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gta_band2.jpg', 'name' => 'gta band', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/mazda.jpg', 'name' => 'mazda', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/bike.jpg', 'name' => 'cartoon bike', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/mazda2.jpg', 'name' => 'mazda rx7', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/anime_naruto.jpg', 'name' => 'anime naruto', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/ferrari.jpg', 'name' => 'ferrari', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/supra.jpg', 'name' => 'toyota supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gun.jpg', 'name' => 'cartoon gun', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sigarets.jpg', 'name' => 'cartoon sigarets', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gang.jpg', 'name' => 'cartoon gang', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/cola.jpg', 'name' => 'pixel cola', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/waves.jpg', 'name' => 'cartoon waves', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/air_force.jpg', 'name' => 'cartoon air force', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick_morty.jpg', 'name' => 'rick and morty', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nft.jpg', 'name' => 'nft teddy', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/takata.jpg', 'name' => 'cartoon takata', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nft_morty.jpg', 'name' => 'nft morty', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gang2.jpg', 'name' => 'black gang', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/skvid.jpg', 'name' => 'skvid', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/m8.jpg', 'name' => 'cartoon m8', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/cartoon_woman.jpg', 'name' => 'cartoon woman', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick.jpg', 'name' => 'rick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/patrick.jpg', 'name' => 'patrick star', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view2.jpg', 'name' => 'beautiful sunset', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view3.jpg', 'name' => 'cartoon forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/portals.jpg', 'name' => 'cartoon portal', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/film_wallpaper.jpg', 'name' => 'breaking bad', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/collab.jpg', 'name' => 'collab', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gta_band3.jpg', 'name' => 'gta band', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/tom.jpg', 'name' => 'cool tom', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/m2.jpg', 'name' => 'cartoon bmw m2', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view4.jpg', 'name' => 'watter view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/aki_nft.jpg', 'name' => 'aki nft', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gang_boy.jpg', 'name' => 'boy gang', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/Tom2.jpg', 'name' => 'tom talking', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gang_near.jpg', 'name' => 'near gang', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nike.jpg', 'name' => 'nike man', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view5.jpg', 'name' => 'sea view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/flower.jpg', 'name' => 'red flower', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sky2.jpg', 'name' => 'orange sky', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick2.jpg', 'name' => 'rick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/bob.jpg', 'name' => 'bob', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/forest.jpg', 'name' => 'green forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/supra2.jpg', 'name' => 'white cartoon supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/cat.jpg', 'name' => 'cool cat', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/white_bang.jpg', 'name' => 'white band', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/patric.jpg', 'name' => 'patric', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/breaking_bad.jpg', 'name' => 'breaking bad', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/drake.jpg', 'name' => 'drake drawing', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view6.jpg', 'name' => 'river view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/pink_view.jpeg', 'name' => 'pink view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nft2.jpg', 'name' => 'no face nft', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/porsche.jpg', 'name' => 'porsche', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/garage.jpg', 'name' => '3D garage', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/blue_milk.jpg', 'name' => 'blue milk', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/black_nissan.jpg', 'name' => 'black nissan z', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/silvia3.jpg', 'name' => 'silvia s15', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sea2.jpg', 'name' => 'evening sea', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/russia.jpg', 'name' => 'russia snow', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gtr.jpg', 'name' => 'purple gtr', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/bandana.jpg', 'name' => 'black bandana', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nft3.jpg', 'name' => 'nft gang', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/toyota.jpg', 'name' => 'cartoon toyota', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/sea3.jpg', 'name' => 'sea view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/mazda_rx7.jpg', 'name' => 'mazda rx7', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/view_house.jpeg', 'name' => 'house view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/lambo.jpg', 'name' => 'green lambo', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/uaz.jpg', 'name' => 'uaz', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/dodge.jpg', 'name' => 'purple dodge', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/skyline.jpg', 'name' => 'skyline', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/silvia4.jpg', 'name' => 's15 silvia', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/forest_view.jpg', 'name' => 'forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/supra3.jpg', 'name' => 'supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rx.jpg', 'name' => 'supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick3.jpg', 'name' => 'rick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gelic.jpg', 'name' => 'black gelic', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick4.jpg', 'name' => 'rick cucumber', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/my_leg.jpg', 'name' => 'my leg', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/med.jpg', 'name' => 'med', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/game_pad2.jpg', 'name' => 'game pad', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/drift.jpg', 'name' => 'drift', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/city.jpg', 'name' => 'city', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nft4.jpg', 'name' => 'white nft dog', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/lada.jpg', 'name' => 'white nft dog', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/gelic2.jpg', 'name' => 'blue gelic', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick_fanta.jpg', 'name' => 'rick fanta', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/dragon.jpg', 'name' => 'dragon', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/nike2.jpg', 'name' => 'nike box', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/supra4.jpg', 'name' => 'orange supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 0, 'img' => 'res/wallpapers/rick_morty2.jpg', 'name' => 'rick and morty', 'free_price' => 'free', 'price' => ''],
            #phone
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/warning.jpg', 'name' => 'wave warning', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/rick5.jpg', 'name' => 'rick on black', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/skyline3.jpg', 'name' => 'skyline on gray', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/silvia5.jpg', 'name' => 'silvia s15', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/alpreza.jpg', 'name' => 'alpreza', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/kfc.jpg', 'name' => 'night kfc', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/street.jpg', 'name' => 'dark street', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/f1.jpg', 'name' => 'f1', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/dragon2.jpg', 'name' => 'dragon', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/skyline4.jpg', 'name' => 'skyline', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/dragon3.jpg', 'name' => 'dragon', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/evening.jpg', 'name' => 'american evening', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/forest2.jpg', 'name' => 'purple forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/ferrari2.jpg', 'name' => 'ferrari on view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/rick_supra.jpg', 'name' => 'rick and supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/mark2.jpg', 'name' => 'mark 2', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/rick_morty3.jpg', 'name' => 'rick and morty', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/gelick.jpg', 'name' => 'gray gelick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/black_gelick.jpg', 'name' => 'gelick with dog', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/breaking_bad2.jpg', 'name' => 'breaking bad', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/$.jpg', 'name' => '100 dollar', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/shark.jpg', 'name' => 'black shark', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/supreme.jpg', 'name' => 'supreme', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/nike3.jpg', 'name' => 'nike', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/winter.jpg', 'name' => '9 deg', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/house.jpg', 'name' => 'night house', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/off_white.jpg', 'name' => 'off white', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/gelic3.jpg', 'name' => 'white gelic', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/off_white2.jpg', 'name' => 'off white', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/house2.jpg', 'name' => 'in house', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/thrasher.jpg', 'name' => 'thrasher', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/gelic4.jpg', 'name' => 'gelic', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/ninja.jpg', 'name' => 'ninja', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/rick6.jpg', 'name' => 'rick lv', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/forest3.jpg', 'name' => 'dark forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/lambo3.jpg', 'name' => 'white lambo', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/lilo.jpg', 'name' => 'stitch', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/house3.jpg', 'name' => 'one house', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/snow.jpg', 'name' => 'snow', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/ferrari3.jpg', 'name' => 'ferrari', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/road.jpg', 'name' => 'road', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/sea4.jpg', 'name' => 'evening sea', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/gearl.jpg', 'name' => 'gearl', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/911.jpg', 'name' => 'porsche 911', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/tom3.jpg', 'name' => 'cool tom', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/happy.jpg', 'name' => 'happy skvid', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/road2.jpg', 'name' => 'city road', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/air.jpg', 'name' => 'nike air', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/water.jpg', 'name' => 'water', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/rick8.jpg', 'name' => 'rick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/cat_supreme.jpg', 'name' => 'supreme cat', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/palm_angels.jpg', 'name' => 'palm angels', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/jordan.jpg', 'name' => 'jordan', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/la_ferrari.jpg', 'name' => 'la ferrari', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/restorant.jpg', 'name' => 'restorant', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/house4.jpg', 'name' => 'house', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/house_view.jpg', 'name' => 'house view', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/city2.jpg', 'name' => 'pink city', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/waves2.jpg', 'name' => '3d waves', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/snake.jpg', 'name' => 'snake', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/f1_2.jpg', 'name' => 'cartoon f1', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/sun.jpg', 'name' => 'angry sun', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/indian_city.jpg', 'name' => 'night city', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/hart.jpg', 'name' => 'snow hart', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/cards.jpg', 'name' => 'cards', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/911.jpg', 'name' => 'porsche 911', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/planet.jpg', 'name' => 'planet', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/phone_call.jpg', 'name' => 'phone call', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/city3.jpg', 'name' => 'city', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/smile.jpg', 'name' => 'smile', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/night_forest.jpg', 'name' => 'night forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/old_america.jpg', 'name' => 'old america', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/purple_ninja.jpg', 'name' => 'purple ninja', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/gtr2.jpg', 'name' => 'nissan gtr', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/bugratti.jpg', 'name' => 'white bugratti', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/nike4.jpg', 'name' => 'nike', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 1, 'img' => 'res/wallpapers/m4.jpg', 'name' => 'bmw m4', 'free_price' => 'free', 'price' => ''],
            #tablet
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/car.jpg', 'name' => 'in car', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/water2.jpg', 'name' => 'wave', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/z.jpg', 'name' => 'nissan z', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/porsche911.jpg', 'name' => 'porsche 911', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/mazda3.jpg', 'name' => 'white mazda', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/forest4.jpg', 'name' => 'night forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/road3.jpg', 'name' => 'night forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/party.jpg', 'name' => 'party', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/yellow_honda.jpg', 'name' => 'yellow honda', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/morning.jpg', 'name' => 'anime morning', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/los_santas.jpg', 'name' => 'los santas', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/night.jpg', 'name' => 'cartoon night', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/sky3.jpg', 'name' => 'blue sky', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/forest5.jpg', 'name' => 'night forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/forest6.jpg', 'name' => 'night forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/forest7.jpg', 'name' => 'forest', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/cyberpunk.jpg', 'name' => 'cyberpunk car', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/supra5.jpg', 'name' => 'stock supra', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/m3.jpg', 'name' => 'bmw m3', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/river.jpg', 'name' => 'on the river', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/bus.jpg', 'name' => 'night bus', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/moto.jpg', 'name' => 'hell cat bike', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/honda.jpg', 'name' => 'white honda', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 2, 'img' => 'res/wallpapers/drift_supra.jpg', 'name' => 'supra in drift', 'free_price' => 'free', 'price' => ''],
            #computer
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/3d_sun.jpg', 'name' => '3d sun', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/rick_morty4.jpg', 'name' => 'rick and morty', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/black_cat.jpg', 'name' => 'black cat', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/rick9.jpg', 'name' => 'rick', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/chil.jpg', 'name' => 'forest chill', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/city4.jpg', 'name' => 'night city', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/windows10.jpg', 'name' => 'windows 10', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 3, 'img' => 'res/wallpapers/bmw.jpg', 'name' => 'bmw', 'free_price' => 'free', 'price' => ''],
            #laptop
            ['class' => '', 'category' => 4, 'img' => 'res/wallpapers/bmw.jpg', 'name' => 'bmw', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 4, 'img' => 'res/wallpapers/bmw.jpg', 'name' => 'bmw', 'free_price' => 'free', 'price' => ''],
            #price
            ['class' => '', 'category' => 5, 'img' => 'res/wallpapers/payment_rolex.jpg', 'name' => 'thank you god', 'free_price' => '', 'price' => '1$'],
            ['class' => '', 'category' => 5, 'img' => 'res/wallpapers/city5.jpg', 'name' => 'night city', 'free_price' => '', 'price' => '1$'],
            ['class' => '', 'category' => 5, 'img' => 'res/wallpapers/city7.jpg', 'name' => 'city', 'free_price' => '', 'price' => '1$'],
            ['class' => '', 'category' => 5, 'img' => 'res/wallpapers/dolars.jpg', 'name' => 'dollar cross', 'free_price' => '', 'price' => '1$'],
            #game
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/gta_map.jpg', 'name' => 'gta 5 map', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/gta_map2.jpg', 'name' => 'gta 5 map', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/san_andreas.jpg', 'name' => 'gta san andreas', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/watchdogs.jpg', 'name' => 'watch dogs 2', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/watchdogs2.jpg', 'name' => 'watch dogs 2', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/cyberpunk3.jpg', 'name' => 'cyberpunk', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/lambo_forza.jpg', 'name' => 'forza horizon 5', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/gta5.jpg', 'name' => 'gta 5', 'free_price' => 'free', 'price' => ''],
            ['class' => '', 'category' => 6, 'img' => 'res/wallpapers/gta_five.jpg', 'name' => 'gta 5', 'free_price' => 'free', 'price' => ''],
            ['class' => 'computer_wallpaper', 'category' => 6, 'img' => 'res/wallpapers/cyberpunk_game.jpg', 'name' => 'cyberpunk', 'free_price' => 'free', 'price' => ''],
            #view
            ['class' => 'computer_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/view_river.jpeg', 'name' => 'view river', 'free_price' => 'free', 'price' => ''],
            ['class' => 'computer_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/view_bridge.jpg', 'name' => 'view bridge', 'free_price' => 'free', 'price' => ''],
            ['class' => 'computer_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/night_city_view.jpeg', 'name' => 'night city view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'computer_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/view_city.jpg', 'name' => 'view city', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/blue_view.jpg', 'name' => 'blue view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/city_view.jpg', 'name' => 'city view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/road_view.jpg', 'name' => 'road view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/forest_view2.jpg', 'name' => 'forest view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'computer_wallpaper', 'category' => 7, 'img' => 'res/wallpapers/forest_view2.jpg', 'name' => 'forest view', 'free_price' => 'free', 'price' => ''],
            #technology
            ['class' => 'phone_wallpaper', 'category' => 8, 'img' => 'res/wallpapers/porsche2.jpg', 'name' => 'porsche', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 8, 'img' => 'res/wallpapers/koenigsegg.jpg', 'name' => 'koenigsegg', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 8, 'img' => 'res/wallpapers/bmw_m4.jpg', 'name' => 'bmw m4', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 8, 'img' => 'res/wallpapers/sky_line.jpg', 'name' => 'sky line', 'free_price' => 'free', 'price' => ''],
            #anime
            ['class' => 'phone_wallpaper', 'category' => 9, 'img' => 'res/wallpapers/dark_man.jpg', 'name' => 'dark man', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 9, 'img' => 'res/wallpapers/red_sky.jpg', 'name' => 'red sky', 'free_price' => 'free', 'price' => ''],
            #color_theme
            ['class' => 'phone_wallpaper', 'category' => 10, 'img' => 'res/wallpapers/green_wether.jpg', 'name' => 'green wether', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 11, 'img' => 'res/wallpapers/purple_car_view.jpg', 'name' => 'purple car view', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 12, 'img' => 'res/wallpapers/blue_city.jpg', 'name' => 'blue city', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 13, 'img' => 'res/wallpapers/yellow_wall.jpg', 'name' => 'yellow wall', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 14, 'img' => 'res/wallpapers/red_city.jpg', 'name' => 'red city', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 15, 'img' => 'res/wallpapers/gray_road.jpg', 'name' => 'gray road', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 16, 'img' => 'res/wallpapers/pink_city.jpg', 'name' => 'pink city', 'free_price' => 'free', 'price' => ''],
            ['class' => 'phone_wallpaper', 'category' => 17, 'img' => 'res/wallpapers/white_sky.jpg', 'name' => 'white sky', 'free_price' => 'free', 'price' => ''],
        ]);
    }
}
